# Generated by Django 5.0.3 on 2024-07-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_giftcard_delete_pricerule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metafield',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
