# Generated by Django 5.0.3 on 2024-07-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_metafield_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metafield',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
