# Generated by Django 5.0.3 on 2024-07-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_metafield_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('arguments', models.JSONField()),
                ('body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('path', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('subject_id', models.BigIntegerField()),
                ('subject_type', models.CharField(max_length=50)),
                ('verb', models.CharField(max_length=50)),
            ],
        ),
    ]
